### ISSUE TITLE
"A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by Phosphor303** [bluedaniel/Kakapo-app#10]
Heyho,

wanted to try Kakapo today.

After installation the main window appeared with a neverending loading symbol. Since closing the app, every time I try to start it I get an error popup disclaiming "A JavaScript error occurred in the main process" and the following error log:

https://gist.github.com/Phosphor303/ce708ef144db55a55c5b

Cheers

OS X 10.11.3

**Comment by bluedaniel** [comment]
Thanks, seems like there is an issue with the settings.json being malformed in the userData path. I'll have a look now.
