### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by MeoBeoI** [bluedaniel/Kakapo-app#14]
I have the same issue as #10 
This is Kakapo for `MacOS`
[Issue image](https://www.dropbox.com/s/oqdxxjgmzkpk661/Screenshot%202016-03-23%2023.52.50.png)

OSX 10.11.2

**Comment by jkurei** [comment]
Exact same issue here. MBPr with 10.11.3.

First time I ran the app, it got stuck, showing a glowing circle. I thought it was loading, or may be downloading sounds, but was taking too much and had to go. Next time I tried it I got that. 

I downloaded the app yesterday, in the afternoon, in case it's relevant.

**Comment by bluedaniel** [comment]
There will be a new release today with loads of new fixes in, I'm just finalising some default playlists and then will be pushing it.

Thanks for the reports!

**Comment by bluedaniel** [comment]
Fixed in new v1.3! :smile: 
232511a62cef2976490ec3d5e5d86dc348208e37
