### ISSUE TITLE
Airfoil

### ISSUE THREAD

**Issue by ocap112** [bluedaniel/Kakapo-app#18]
Hi again. I use Roughamobas Airfoil to stream ambient sounds to different speakers, but i can't seem to ad kakapo as a source of sound in airfoil (nor loopback).
Any chance this might be resolved?

Use OS X

**Comment by bluedaniel** [comment]
Hi @ocap112, thanks for the report.

I did get it working in Airfoil by selecting 'other' and then choosing the Kakapo.app file in Applications.

Can you give this a try to get it working?

Thanks

**Comment by ocap112** [comment]
My bad. Moved it to applications from Downloads, works just fine now. Feel stupid =/

Thanks for a great app!

**Comment by bluedaniel** [comment]
No problem, glad your enjoying it!
