### ISSUE TITLE
Playlists feature is showing the domain twice

### ISSUE THREAD

**Issue by rtpHarry** [bluedaniel/Kakapo-app#19]
I just clicked on the share playlist button and its showing me this:

![image](https://cloud.githubusercontent.com/assets/1038062/14932746/aa550e56-0e73-11e6-9bcc-f95b4dbd3a3a.png)

Running it in-browser on Chrome Version 50.0.2661.94 m (64-bit), Windows 10

**Comment by bluedaniel** [comment]
@rtpHarry Thanks for the catch! I'll fix this tonight, I'm probably repeating the strings in the view

**Comment by bluedaniel** [comment]
Fixed by cbb478d2627ad3cf615129aea385b2adf4ef24e9
