### ISSUE TITLE
Will there be a Linux client?

### ISSUE THREAD

**Issue by kmf** [bluedaniel/Kakapo-app#20]
maybe? no?

**Comment by bluedaniel** [comment]
@kmf yes certainly there could be. Electron does build Linux clients but I've not got a Linux machine to test on.

I've just got a new machine at home though, I'll give it a try soon and include it in the next release

**Comment by kmf** [comment]
awesome

**Comment by kmf** [comment]
awesome

**Comment by kmf** [comment]
awesome

**Comment by kmf** [comment]
awesome

**Comment by iommu** [comment]
So i guess not then? :(

**Comment by Ziggornif** [comment]
@bluedaniel i just try to run your app on a Ubuntu 16.04 distro and it'f work fine !
I just add this line on your script mp3-to-ogg.sh and give execute permission. 
```
#!/bin/bash
# Script to convert mp3 to ogg files
# Website and desktop uses ogg files
for file in sounds/*.mp3;
   do ffmpeg -i "${file}" -acodec libvorbis "${file/%mp3/ogg}";
done
```
