### ISSUE TITLE
Email functionality

### ISSUE THREAD

**Issue by mylonasg88** [bluedaniel/Kakapo-app#5]
Clicking to send e-mail opens default e-mail app and an Electron window, which stays is empty. It is possible to close it clicking on close button on top left corner but feels like empty Electron windows should not appear as if has no functionality at all.

OS : X Yosemite 10.10.5

**Comment by bluedaniel** [comment]
Thanks @mylonasg88, I didn't realise it opens the default email app, on mine it opens gmail.com within the Electron window.

I'll look at improving the electron windows, your right in that an empty one is a bug.

**Comment by bluedaniel** [comment]
I've removed the share functionality for now until I can figure this out.
