### ISSUE TITLE
SyntaxError occurs in Babel 6.4.0 while building modules

### ISSUE THREAD

**Issue by re-fort** [bluedaniel/Kakapo-app#8]
While building modules,  SyntaxError occurs :(
Apparently  semicolons are required after class properties in Babel  6.4.0

See https://github.com/feross/standard/issues/372

**Comment by bluedaniel** [comment]
Thanks, I had noticed yesterday as I've got a bunch of new commits to push tonight.

All the dependencies will be updated, including fixes for the new class syntax.

Daniel

**Comment by bluedaniel** [comment]
Fixed in f3527bf9e3d2e18accb309aad57bc166a21b9ad6
